version: "2.4"

services:

  studeeper_front_dev:

    networks:
      - std_network

    image: "romanidze/std_frontend_dev:latest"

    build:
      context: system_front
      dockerfile: docker/app/dev/Dockerfile
      args:
        - DEV_PORT=8001

    container_name: std_frontend_dev

    volumes: 
      - ./system_front:/code

    command: launch-dev

    ports:
      - "8001:8001"

    environment:
      - CHOKIDAR_USEPOLLING=true

  studeeper_front_prod:

    networks:
      - std_network

    image: "romanidze/std_frontend_prod:latest"

    build:
      context: system_front
      dockerfile: docker/app/prod/Dockerfile

    container_name: std_frontend_prod

    command: launch-prod

    volumes:
      - ./system_front/dist:/usr/share/nginx/html

    ports:
      - "3000:3000"

networks:
  std_network: