version: "2.4"

services:

  studeeper_front:

    networks:
      - std_network

    image: "romanidze/std_frontend:latest"

    build:
      context: system_front
      dockerfile: docker/app/Dockerfile
      args:
        - PROD_PORT=3000
        - DEV_PORT=8001

    container_name: std_frontend

    volumes: 
      - ./system_front:/code

    command: launch-dev

    ports:
      - "3000:3000"
      - "8001:8001"

networks:
  std_network: