version: "2.4"

services: 

  mongo:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: mongo

    container_name: std_mongo

  redis:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: redis

    container_name: std_redis

  zookeeper:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: zookeeper-service

  kafka:

    networks:
      - std_network

    extends:
    
      file: backend/docker-compose.yml
      service: kafka-service

    depends_on:
      - zookeeper

  kafka-topics:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: kafka-topics-init

    depends_on:
      - kafka 

  clickhouse:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: clickhouse

    depends_on:
      - kafka 
      - system_backend

  clickhouse-gui:

    networks:
      - std_network

    extends:

      file: backend/docker-compose.yml
      service: clickhouse-gui

    depends_on:
      - clickhouse

    links:
      - clickhouse

  system_backend:

    networks:
      - std_network

    depends_on:
      - mongo
      - redis
      - kafka

    extends: 
      
      file: backend/docker-compose.yml
      service: system_service

    container_name: std_system_app

  files_backend:

    networks:
      - std_network

    depends_on:
      - mongo
      - redis
      - kafka
      - system_backend

    extends:

      file: backend/docker-compose.yml
      service: file_service

    container_name: std_files_app

  frontend:

    networks:
      - std_network

    extends:

      file: frontend/docker-compose.yml
      service: studeeper_front_prod

    container_name: std_frontend

    depends_on:
      - system_backend
      - files_backend

networks:
  std_network: