version: "2.4"

services:
  system_service:
    networks:
      - std_network

    image: "romanidze/std_system_app:latest"

    build:
      context: system_service
      dockerfile: docker/app/Dockerfile
      args:
        - PROD_JVM_OPTS=-Xmx200m
        - PORT=8000
        - DOCKERIZE_VERSION=v0.6.1

    container_name: std_system_app

    volumes:
      - ./system_service:/code
      - ./system_service/build/libs:/code/build/libs

    command: launch-prod

    ports:
      - "8000:8000"

  file_service:
    networks:
      - std_network

    image: "romanidze/std_files_app:latest"

    build:
      context: file_service
      dockerfile: docker/app/Dockerfile
      args:
        - PORT=5000

    container_name: std_files_app

    volumes:
      - ./file_service:/code

    command: launch-app

    ports:
      - "5000:5000"

  mongo:
    networks:
      - std_network

    image: "bitnami/mongodb:4.2.1"

    container_name: std_mongo

    ports:
      - "27017:27017"

    environment:
      - MONGODB_USERNAME=studeeper_user
      - MONGODB_PASSWORD=studeeper_pwd
      - MONGODB_DATABASE=studeeper_db

  redis:
    networks:
      - std_network

    image: "redis:5.0.7-alpine"

    container_name: std_redis

    ports:
      - "6379:6379"

networks:
  std_network:
