version: "2.4"

services:
  app:
    networks:
      - std_network

    image: "romanidze/studeeper_app:latest"

    build:
      context: system_service
      dockerfile: docker/app/Dockerfile
      args:
        - PROD_JVM_OPTS=-Xmx200m
        - PORT=8000
        - DOCKERIZE_VERSION=v0.6.1

    container_name: std_app

    depends_on:
      - mongo
      - clickhouse

    command: launch-prod

    ports:
      - "8000:8000"

  mongo:
    networks:
      - std_network

    image: "bitnami/mongodb:4.2.1"

    container_name: std_mongo

    ports:
      - "27017:27017"

    environment:
      - MONGODB_USERNAME=studeeper_user
      - MONGODB_PASSWORD=studeeper_pwd
      - MONGODB_DATABASE=studeeper_db

  clickhouse:
    networks:
      - std_network

    image: "yandex/clickhouse-server:19.17.6.36"

    container_name: std_clickhouse

    ports:
      - "8401:8123"
      - "8501:9000"

    volumes:
      - "./docker_config/clickhouse/sql:/docker-entrypoint-initdb.d"
      - "./docker_config/clickhouse/users:/etc/clickhouse-server/users.d"

  redis:
    networks:
      - std_network

    image: "redis:5.0.7-alpine"

    container_name: std_redis

    ports:
      - "6379:6379"

networks:
  std_network:
    driver: bridge
