spring:

  application:

    name: studeeper-backend

  data:

    mongodb:

      host: localhost
      port: 27017
      database: studeeper_db
      username: studeeper_user
      password: studeeper_pwd

server:

  port: 8000

logging:

  config: classpath:logging/logback-spring.xml