spring:
  application:
    name: studeeper-backend

  data:
    mongodb:
      host: std_mongo
      port: 27017
      database: studeeper_db
      username: studeeper_user
      password: studeeper_pwd

  redis:
    host: std_redis
    port: 6379
    database: 0

server:
  port: 8000

files:
  server:
    host: std_files_app
    port: 5000

jwt:
  properties:
    header: Authorization
    prefix: Bearer
    secret-key: fnreskjdfn4p3ithn3q[04tfraf
    expires-at: 600

logging:
  config: classpath:logging/logback-spring.xml

sendgrid:
  config:
    base-url: https://example
    api-key: kkhgckgcgckgchkgckgc
    mail-endpoint: /v3/mail/send 
