spring:
  application:
    name: studeeper-backend

  data:
    mongodb:
      host: std_mongo_test
      port: 27018
      database: studeeper_db
      username: studeeper_user
      password: studeeper_pwd

  redis:
    host: std_redis_test
    port: 6380
    database: 0

server:
  port: 8000

files:
  server:
    host: std_files_app
    port: 5001

jwt:
  properties:
    header: Authorization
    prefix: Bearer
    secret-key: fnreskjdfn4p3ithn3q[04tfraf
    expires-at: 600

logging:
  config: classpath:logging/logback-spring.xml
