server:
  host: std_files_app
  port: 5000

redis:
  host: std_redis
  port: 6379
  db: 0

mongo:
  host: std_mongo
  port: 27017
  database: studeeper_db
  user: studeeper_user
  password: studeeper_pwd
