server:
  host: std_files_app
  port: 5000

redis:
  host: std_redis
  port: 6379
  db: 0

mongo:
  host: std_mongo
  port: 27017
  database: studeeper_db
  user: studeeper_user
  password: studeeper_pwd

kafka:
  host: std_kafka
  port: 9092
  topics: 
    - student_file_source
    - student_facility_source
