server:
  host: std_files_app
  port: 5000

redis:
  host: std_redis_test
  port: 6380
  db: 0

mongo:
  host: std_mongo_test
  port: 27018
  database: studeeper_db
  user: studeeper_user
  password: studeeper_pwd
