host: '0.0.0.0'
port: 5000
title: 'analysis-service'
version: '0.0.1'

is_debug: true

mongo: 
  host: localhost
  port: 27017
  user: studeeper_user
  password: studeeper_pass
  db: studeeper_db

redis_url: 'redis://localhost:5379/0'
hdfs_url: 'hdfs://localhost:8092'