host: '0.0.0.0'
port: 5001
title: 'analysis-service'
version: '0.0.1'

is_debug: true

mongo: 
  host: std_mongo
  port: 27017
  user: studeeper_user
  password: studeeper_pass
  db: studeeper_db

redis:
  host: std_redis
  port: 6379

hdfs_url: 'std_hdfs_namenode:9870'