version: '2.4'

services:

  app:

    image: 'romanidze/studeeper_app:latest'

    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      args:
        JAR_FILE: $JAR_FILE
        JVM_OPTS: $JVM_OPTS
        PORT: ${PORT:-8000}

    container_name: std_app

    ports:
      - '8000:8000'

    env_file:
      - .env

  mongo:

    image: 'bitnami/mongodb:4.2.1'

    container_name: std_mongo

    ports:
      - '27017:27017'

    env_file:
      - .env

  neo4j:

    image: 'bitnami/neo4j:3.5.12'

    container_name: std_neo4j

    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

    env_file:
      - .env