version: "2.4"

services:
  app:
    networks:
      - std_network

    image: "romanidze/studeeper_app:latest"

    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      args:
        - JAR_FILE=build/libs/app.jar
        - JVM_OPTS=-Xmx200m
        - PORT=8000
        - DOCKERIZE_VERSION=v0.6.1

    container_name: std_app

    depends_on:
      - mongo

    environment:
      - SPRING_PROFILES_ACTIVE=docker

    command: launch

    ports:
      - "8000:8000"

  mongo:
    networks:
      - std_network

    image: "bitnami/mongodb:4.2.1"

    container_name: std_mongo

    ports:
      - "27017:27017"

    environment:
      - MONGODB_USERNAME=studeeper_user
      - MONGODB_PASSWORD=studeeper_pwd
      - MONGODB_DATABASE=studeeper_db

networks:
  std_network:
    driver: bridge
